development:
   AWS_ACCESS_KEY_ID: 'AKIAIZ4BFVKM3RA642KQ'
   AWS_SECRET_ACCESS_KEY: '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'
   S3_BUCKET: 'projectmeal-dev'
test:
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-test'
production:
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-production'